import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("photo code debug reviewer runs from v2 pages and reuses scanner OCR auth", async () => {
  const html = await readFile(new URL("../v2/photo-code-debug-review/index.html", import.meta.url), "utf8");
  const js = await readFile(new URL("../v2/assets/photo_code_debug_review.js", import.meta.url), "utf8");
  const apps = await readFile(new URL("../v2/apps/index.html", import.meta.url), "utf8");
  const sw = await readFile(new URL("../v2/sw.js", import.meta.url), "utf8");

  assert.match(html, /\/fifa-sticker-app\/v2\/assets\/site_config\.js/);
  assert.match(html, /\/fifa-sticker-app\/v2\/assets\/photo_code_debug_review\.js/);
  assert.match(html, /#photoCanvas\s*\{/);
  assert.match(html, /\.debugTop\s*\{[\s\S]*?position:\s*static;/);
  assert.match(html, /\.debugStageWrap\s*\{[\s\S]*?min-height:\s*70dvh;/);
  assert.match(html, /#photoCanvas\s*\{[\s\S]*?height:\s*70dvh;[\s\S]*?min-height:\s*520px;/);
  assert.match(html, /\.overlayLegend\s*\{/);
  assert.match(html, /\.debugExplain\s*\{/);
  assert.match(html, /\.anchorLogic\s+ol\s*\{/);
  assert.match(html, /\.anchorCard\s*\{/);
  assert.match(html, /\.anchorImage\s*\{/);
  assert.match(html, /\.algorithmTrace\s*\{/);
  assert.match(html, /\.algorithmStep\s*\{/);
  assert.match(html, /\.stepDecision\s*\{/);
  assert.doesNotMatch(html, /src="\/assets\/photo_code_debug_review\.js/);
  assert.doesNotMatch(html, /OCR bearer token/);

  assert.match(apps, /\/fifa-sticker-app\/v2\/photo-code-debug-review\//);
  assert.match(apps, /Photo Code Deep Dive/);

  assert.match(js, /from "\/fifa-sticker-app\/v2\/assets\/ocr_backend\.js/);
  assert.match(js, /ocrToken\(\)/);
  assert.match(js, /recognitionUrl\(url\)/);
  assert.match(js, /headers\.set\("Authorization", `Bearer \$\{activeToken\}`\)/);
  assert.match(js, /const SNAPSHOTS =/);
  assert.match(js, /01 Big Photo/);
  assert.match(js, /02 Card Zone/);
  assert.match(js, /03 Pill And OCR/);
  assert.match(js, /04 Orientation \/ Anchors/);
  assert.match(js, /function drawSnapshots\(slot\)/);
  assert.match(js, /function renderAlgorithmTrace\(slot\)/);
  assert.match(js, /function algorithmSteps\(slot\)/);
  assert.match(js, /function renderAlgorithmStep\(step, number, slot\)/);
  assert.match(js, /showTitle:\s*true/);
  assert.match(js, /Start from the photo/);
  assert.match(js, /Check the four anchors/);
  assert.match(js, /Render only computed overlays/);
  assert.match(js, /snapshot:\s*"pill"/);
  assert.match(js, /snapshot:\s*"card"/);
  assert.match(js, /snapshot:\s*"orientation"/);
  assert.match(js, /renderSnapshotShell\(snapshotById\(section\.snapshot\), \{ embedded:\s*true,\s*slot \}\)/);
  assert.match(js, /const imageSnippet = snapshot \? renderSnapshotImage\(slot, snapshot\) : "";/);
  assert.match(js, /function renderSnapshotImage\(slot, kind\)/);
  assert.match(js, /function renderSnapshotDataImage\(slot, kind\)/);
  assert.match(js, /renderSnapshotDataImage\(slot, snapshot\.id\)/);
  assert.match(js, /canvasEl\.toDataURL\("image\/jpeg", 0\.86\)/);
  assert.match(js, /function renderOverlayLegend\(slot = null\)/);
  assert.match(js, /function hasCardBoundary\(slot\)/);
  assert.match(js, /if \(hasCardBoundary\(slot\)\) \{/);
  assert.match(js, /No yellow card boundary is shown/);
  assert.match(js, /function renderCheckExplanation\(check, slot, snapshot\)/);
  assert.match(js, /function renderAnchorLogic\(slot\)/);
  assert.match(js, /function renderAnchorCard\(title, anchor\)/);
  assert.match(js, /function renderAnchorImage\(anchor\)/);
  assert.match(js, /function drawAnchorSnapshot\(canvasEl, anchor\)/);
  assert.match(js, /selected_code_anchor/);
  assert.match(js, /observed_code_anchors/);
  assert.match(js, /nearby_code_anchors/);
  assert.match(js, /anchor\.normalized_box/);
  assert.match(js, /function checkSnapshotKind\(check\)/);
  assert.match(js, /normalized_code_text_box/);
  assert.doesNotMatch(js, /const OCR_TOKEN_KEY =/);

  assert.match(sw, /const BUILD_ID = "build-a82f4c19d6e7"/);
  assert.match(sw, /fifa-card-apps-fifa-sticker-app-v2-\$\{BUILD_ID\}/);
  assert.match(sw, /\/fifa-sticker-app\/v2\/photo-code-debug-review\//);
  assert.match(sw, /\/fifa-sticker-app\/v2\/assets\/photo_code_debug_review\.js/);
});
